export const Colors = {
  primary:       '#1A56DB',
  primaryLight:  '#EBF5FF',
  primaryDark:   '#1143A3',
  success:       '#057A55',
  successLight:  '#F3FAF7',
  warning:       '#B45309',
  warningLight:  '#FFFBEB',
  error:         '#C81E1E',
  errorLight:    '#FDF2F2',
  info:          '#1C64F2',
  infoLight:     '#EBF5FF',
  white:         '#FFFFFF',
  background:    '#F9FAFB',
  surface:       '#FFFFFF',
  border:        '#E5E7EB',
  divider:       '#F3F4F6',
  textPrimary:   '#111928',
  textSecondary: '#4B5563',
  textTertiary:  '#6B7280',
  textDisabled:  '#9CA3AF',
  textInverse:   '#FFFFFF',
} as const;
